"""Final build hygiene: retain source changes, remove generated bytecode."""
from pathlib import Path
import subprocess
tracked=subprocess.check_output(['git','ls-files','-z']).decode().split('\0')
generated=[p for p in tracked if p and ('__pycache__' in Path(p).parts or p.endswith('.pyc'))]
if generated:
    subprocess.run(['git','rm','--cached','--',*generated],check=True)
p=Path('.gitignore')
s=p.read_text() if p.exists() else ''
for rule in ('__pycache__/','*.py[cod]','.pytest_cache/'):
    if rule not in s.splitlines():
        s+=rule+'\n'
p.write_text(s)
subprocess.run(['git','add','.gitignore'],check=True)
print('Generated bytecode removed from index; tests regenerate ignored local caches only')
